import sqlite3
conn=sqlite3.connect('database.db')
c=conn.cursor()

#c.execute('update customers set contactname = "A", city = "B" where customerid="1"')
#c.execute('update customers set contactname = "Juan" where country = "Mexico"')
#c.execute('delete from customers where customername = "Alfreds Futterkiste"')
#c.execute('select * from customers limit 3')
#c.execute('select * from customers where country = "Germany" limit 3')
#c.execute('select min(price) from products')
#c.execute('select max(price) from products')
#c.execute('select count(*) from products')
#c.execute('select avg(price) from products')
#c.execute('select sum(quantity) from orderdetails')
#c.execute('select customername from customers where customername like "a%"')
#c.execute('select customername from customers where customername like "%a"')
#c.execute('select customername from customers where customername like "%or%"')
#c.execute('select customername from customers where customername like "_r%"')
#c.execute('select customername from customers where customername like "a_%_%"')
#c.execute('select contactname from customers where contactname like "a%o"')
#c.execute('select customername from customers where customername not like "a%"')
#c.execute('select city from customers where city like "ber%"')
#c.execute('select city from customers where city like "%es%"')
#c.execute('select city from customers where city like "_erlin%"')
#c.execute('select city from customers where city like "L_n_on%"')
#c.execute('select city from customers where city like  "[bsp]%"')
#c.execute('select city from customers where city like "[a-c]%"')
#c.execute('select city from customers where city like "[!bsp]%"')
#c.execute('select country from customers where country in ("Germany", "France", "UK")')
#c.execute('select country from customers where country not in ("Germany", "France", "UK")')
#c.execute('select * from customers where country in (select country from suppliers)')
#c.execute('select * from products where price between 10 and 20')
#c.execute('select * from products where price between 10 and 20 and categoryid>3')
#c.execute('select * from products where productname between "Carnarvon Tigers" and "Mozzarella di Giovanni"')
#c.execute('select * from products where productname not between "Carnarvon Tigers" and "Mozzarella di Giovanni"')
#c.execute('select * from orders where orderdate between "04-July-1996" and "09-July-1996"')
#c.execute('select customerid as A from customers')
#c.execute('select customername as B from customers')
#c.execute('select Address, PostalCode, City, Country as Address from customers')
#c.execute('select customerid as c from orders as o where c=4')
#c.execute('select * from orders where customerid =4')


for n in c.fetchall():
    print(n)
conn.commit()
c.close()

